name: CI
on:
  push:
    branches_ignore:
      - 'gh-pages'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npx standard@14.3.4
  build:
    needs: lint
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: upgrade npm
        run: |
          npm install -g npm; npm -v
      - name: get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: cache node modules
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'windows')
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install
        run: npm ci
      - name: run integration tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test:integration
      - name: prepare for notarization
        if: startsWith(matrix.os, 'macos')
        run: |
          mkdir -p ~/private_keys/
          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8
      - name: build and release
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          max_attempts: 5
        env:
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
      - name: read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: package.json
      - name: get version
        id: version
        uses: gr2m/get-json-paths-action@v1.0.2
        with:
          json: ${{ steps.package.outputs.content }}
          version: 'version'
      - name: get product name
        id: productName
        uses: gr2m/get-json-paths-action@v1.0.2
        with:
          json: ${{ steps.package.outputs.content }}
          productName: 'productName'
      - name: archive mac dmg
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v1
        with:
          name: mac
          path: dist/${{ steps.productName.outputs.productName }}-${{ steps.version.outputs.version }}.dmg
      - name: archive linux appimage
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: dist/${{ steps.productName.outputs.productName }}-${{ steps.version.outputs.version }}.AppImage
      - name: archive windows setup
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v1
        with:
          name: windows
          path: dist/${{ steps.productName.outputs.productName }} Setup ${{ steps.version.outputs.version }}.exe
